### ISSUE TITLE
method is fout

### ISSUE THREAD

**Issue by Theo-denBlanken** [Spyrincho/formulieren#5]
Je hebt feedback gekregen van **Theo-denBlanken**
op:
```c
<form action="http://bla.hosts.ma-cloud.nl/pop.php" method="post"> 
```

URL: https://github.com/Spyrincho/formulieren/blob/master/formulier.html

Feedback: dus geen verwerking van het formulier[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"debdfe0deef9b40b672e0fef36d0fd9f88669d21","path":"formulier.html","reviewer":"Theo-denBlanken"}')

**Comment by Spyrincho** [comment]
Als het goed is moet die nu correct zijn.
